# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/filedemo/adress.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/filedemo/adress.proto',
  package='org.example.protobuf.message',
  syntax='proto3',
  serialized_options=b'\n\034org.example.protobuf.message',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dmessage/filedemo/adress.proto\x12\x1corg.example.protobuf.message\"\x1c\n\x06\x41\x64ress\x12\x12\n\nadressName\x18\x01 \x01(\tB\x1e\n\x1corg.example.protobuf.messageb\x06proto3'
)




_ADRESS = _descriptor.Descriptor(
  name='Adress',
  full_name='org.example.protobuf.message.Adress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='adressName', full_name='org.example.protobuf.message.Adress.adressName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['Adress'] = _ADRESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Adress = _reflection.GeneratedProtocolMessageType('Adress', (_message.Message,), {
  'DESCRIPTOR' : _ADRESS,
  '__module__' : 'message.filedemo.adress_pb2'
  # @@protoc_insertion_point(class_scope:org.example.protobuf.message.Adress)
  })
_sym_db.RegisterMessage(Adress)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
