# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/person.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from message.filedemo import adress_pb2 as message_dot_filedemo_dot_adress__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/person.proto',
  package='org.example.protobuf.message',
  syntax='proto3',
  serialized_options=b'\n\034org.example.protobuf.messageB\rPersonMessage',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14message/person.proto\x12\x1corg.example.protobuf.message\x1a\x1dmessage/filedemo/adress.proto\"=\n\x03Sex\x12\x36\n\x07sexType\x18\x01 \x01(\x0e\x32%.org.example.protobuf.message.SexType\"\xbd\x02\n\x06Person\x12\x0c\n\x04name\x18\x01 \x03(\t\x12.\n\x03sex\x18\x02 \x01(\x0b\x32!.org.example.protobuf.message.Sex\x12\x37\n\x04high\x18\x03 \x01(\x0b\x32).org.example.protobuf.message.Person.High\x12\x34\n\x06\x41\x64ress\x18\x04 \x01(\x0b\x32$.org.example.protobuf.message.Adress\x12:\n\x03\x62\x61g\x18\x05 \x03(\x0b\x32-.org.example.protobuf.message.Person.BagEntry\x1a\x18\n\x04High\x12\x10\n\x08heighNum\x18\x01 \x01(\x05\x1a*\n\x08\x42\x61gEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01J\x04\x08\t\x10\x0c*\x1d\n\x07SexType\x12\x07\n\x03man\x10\x00\x12\t\n\x05woman\x10\x01\x42-\n\x1corg.example.protobuf.messageB\rPersonMessageb\x06proto3'
  ,
  dependencies=[message_dot_filedemo_dot_adress__pb2.DESCRIPTOR,])

_SEXTYPE = _descriptor.EnumDescriptor(
  name='SexType',
  full_name='org.example.protobuf.message.SexType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='man', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='woman', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=468,
  serialized_end=497,
)
_sym_db.RegisterEnumDescriptor(_SEXTYPE)

SexType = enum_type_wrapper.EnumTypeWrapper(_SEXTYPE)
man = 0
woman = 1



_SEX = _descriptor.Descriptor(
  name='Sex',
  full_name='org.example.protobuf.message.Sex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sexType', full_name='org.example.protobuf.message.Sex.sexType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=146,
)


_PERSON_HIGH = _descriptor.Descriptor(
  name='High',
  full_name='org.example.protobuf.message.Person.High',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='heighNum', full_name='org.example.protobuf.message.Person.High.heighNum', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=416,
)

_PERSON_BAGENTRY = _descriptor.Descriptor(
  name='BagEntry',
  full_name='org.example.protobuf.message.Person.BagEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='org.example.protobuf.message.Person.BagEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='org.example.protobuf.message.Person.BagEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=460,
)

_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='org.example.protobuf.message.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='org.example.protobuf.message.Person.name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sex', full_name='org.example.protobuf.message.Person.sex', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='high', full_name='org.example.protobuf.message.Person.high', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Adress', full_name='org.example.protobuf.message.Person.Adress', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bag', full_name='org.example.protobuf.message.Person.bag', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PERSON_HIGH, _PERSON_BAGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=466,
)

_SEX.fields_by_name['sexType'].enum_type = _SEXTYPE
_PERSON_HIGH.containing_type = _PERSON
_PERSON_BAGENTRY.containing_type = _PERSON
_PERSON.fields_by_name['sex'].message_type = _SEX
_PERSON.fields_by_name['high'].message_type = _PERSON_HIGH
_PERSON.fields_by_name['Adress'].message_type = message_dot_filedemo_dot_adress__pb2._ADRESS
_PERSON.fields_by_name['bag'].message_type = _PERSON_BAGENTRY
DESCRIPTOR.message_types_by_name['Sex'] = _SEX
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.enum_types_by_name['SexType'] = _SEXTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sex = _reflection.GeneratedProtocolMessageType('Sex', (_message.Message,), {
  'DESCRIPTOR' : _SEX,
  '__module__' : 'message.person_pb2'
  # @@protoc_insertion_point(class_scope:org.example.protobuf.message.Sex)
  })
_sym_db.RegisterMessage(Sex)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {

  'High' : _reflection.GeneratedProtocolMessageType('High', (_message.Message,), {
    'DESCRIPTOR' : _PERSON_HIGH,
    '__module__' : 'message.person_pb2'
    # @@protoc_insertion_point(class_scope:org.example.protobuf.message.Person.High)
    })
  ,

  'BagEntry' : _reflection.GeneratedProtocolMessageType('BagEntry', (_message.Message,), {
    'DESCRIPTOR' : _PERSON_BAGENTRY,
    '__module__' : 'message.person_pb2'
    # @@protoc_insertion_point(class_scope:org.example.protobuf.message.Person.BagEntry)
    })
  ,
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'message.person_pb2'
  # @@protoc_insertion_point(class_scope:org.example.protobuf.message.Person)
  })
_sym_db.RegisterMessage(Person)
_sym_db.RegisterMessage(Person.High)
_sym_db.RegisterMessage(Person.BagEntry)


DESCRIPTOR._options = None
_PERSON_BAGENTRY._options = None
# @@protoc_insertion_point(module_scope)
